### ISSUE TITLE
YouTube video alignment keeps defaulting LEFT

### ISSUE THREAD

**Issue by tealshift** [tamius-han/ultrawidify#101]
**Describe the bug**
YouTube. 
It seems to happen when YT autoplays to the next video, either from a playlist or when Autoplay is enabled. I don't remember when I first started seeing this. Maybe a month ago.

**To Reproduce**
Enable autoplay or use a playlist, and wait for it to trigger the next video.
Video gets aligned left, but the controls still work so it can be reset back center. 

**Expected behavior**
Seems like a simple misbehavior.

**Screenshots**
It's definitely just the video alignment setting. 

**Browser and OS**
 * Browser/browser version: Firefox 75.0
 * Operating system: Windows 10
 * Ultrawidify version: 4.4.7

**Comment by tamius-han** [comment]
This should be fixed now (as of 4.4.7.2). Chrome users will have to wait a bit more till extension passes review.

**Comment by rhoot** [comment]
This is happening now in 4.4.8.

**Comment by tealshift** [comment]
@rhoot Yes, I noticed the regression as well. I wondered if maybe YouTube was breaking it with site updates. I've never tried to seriously maintain an extension for a live commercial product (website) but it sounds grueling to keep up. Props to the contributor(s)!

**Comment by tamius-han** [comment]
> I'm typically also running a game at the same time if that may have an effect on it.

That likely has something to do with it. There might be a brief period of time where video's dimensions are 0x0, and that seems to be tripping the extension up. 

The previous solution to this issue was to retry detecting video size for a bit if the video was 0x0. Now, retries absolutely _do_ stop for a while, but the retries are supposed to last for the first few seconds ... which should resolve these issues.

But I guess not. Time to find a better solution I guess.

**Comment by tamius-han** [comment]
Now it should be fixed for real.

Updates should be rolling rather soon.
