### ISSUE TITLE
It actually does work on edge, it's just that some sites are misaligned

### ISSUE THREAD

**Issue by eharo1987** [tamius-han/ultrawidify#105]
doesnt work properly or at all on new edge :(

Youtube: seems to work fine
Netflix: misaligned, not getting 21:9 at all
HBO: does nothing
Prime video: does nothing

**Comment by tamius-han** [comment]
Why do I bother spending time trying to write a bug report template when people just ignore it and don't provide the necessary info (such as: version info) that the template asks for.

> HBO: does nothing
> Prime video: does nothing

These are both paid services and I unfortunately don't have triple digits of spare income to split between five different streaming platforms. That's why there's advanced settings and a [wiki entry on how to use it](https://github.com/tamius-han/ultrawidify/wiki/Fixing-site-incompatibilites-('Advanced-settings')).

Notes to self:

>Netflix: misaligned, not getting 21:9 at all

* Misalignment only happens when trying to set crop on videos where <video>` tag has `style="height: something%;"` attribute. (Worth noting that videos with with this attribute are already in proper aspect ratio). If the video lacks this attribute, everything seems to work fine (except autodetection, but as per store descriptions and especially readme of this repo, autodetection won't always work (DRM-protected sites are the problem)). This suggests that the problem with misalignment must be related to checking for `autoarPreventConditions.videoStyleString.containsString`.

This doesn't happen when trying to use peasant mode (stretch), because `style="height: something%"` correctly prevents extension from doing stretch.

**Comment by eharo1987** [comment]
Hi,

Sorry for not using the template correctly, edge version is 84.0.522.40.

I tried to follow the wiki entry for netflix and primevideo, but I guess I cannot find the correct id/class

**Comment by tamius-han** [comment]
As of 2 months ago, there were some bugs introduced into Edge that prevent this extension from working properly. While misalignment could have been resolved with some user action before, the DRM-protected videos now render completely incorrectly — even without this extension installed.

Due to that, the extension was pulled from Edge Addons store until this issue gets fixed and this issue is considered obsolete as Edge is unsupported.

I am sorry for the inconvenience and ask you to avoid installing this extension from the Chrome Web Store for use with Edge. It will not work (unless you're using Youtube or Twitch).
