### ISSUE TITLE
Video Alignment on Twitch.tv

### ISSUE THREAD

**Issue by Jaden-** [tamius-han/ultrawidify#109]
Video Alignment (Left, Center, Right) works perfectly on Youtube, but not on Twitch. This is with all other settings set to default. It does somewhat work in combination with other settings, like 21:9 mode + Left, but not on its own.

Youtube, Left aligned. Perfect!
![Landscape](https://user-images.githubusercontent.com/8606585/90278789-4abbad00-de68-11ea-998a-ae2fccb3e481.PNG)

Twitch, Left aligned. Black bars on both sides!
![image](https://user-images.githubusercontent.com/8606585/90279566-c0744880-de69-11ea-9f74-f8fe13939b23.png)

Tested on both Chrome and Firefox.

Can you please look into this? Video Alignment is my favorite feature about your plugin!

Thank you so much in advance.

**Comment by tamius-han** [comment]
Note to self: the problem is caused by this:

![image](https://user-images.githubusercontent.com/12505802/93936711-e1f90780-fd26-11ea-9eb7-d8b5595be5b6.png)

Extension doesn't expect `<video>` element to get stretched to full width of the player — instead, it's expected that the video will be of the same aspect ratio as the file it's playing.

Because `<video>` takes up all the space in the player, javascript is like: "hmm, the `<video>` is 2560px wide? And the player is also 2560px wide? Well, 2560px - 2560px is 0 px of vertical edge, so the video is already aligned! :tada:"

This is also the reason why video alignment on [letterboxed content](https://www.twitch.tv/videos/502559613?%3Ft=10m25s) aligns to the wrong end of the monitor (and also cuts off a lil bit extra).

**Comment by tamius-han** [comment]
This bug has been fixed and will be landing on Firefox soon.

Chrome is having a bit of an issue with reviews at the moment though, so this could take weeks on the Chrome side.
