### ISSUE TITLE
Hulu: Video alignment is off

### ISSUE THREAD

**Issue by rmill3r** [tamius-han/ultrawidify#111]
**Describe the bug**
Anything I watch on Hulu, the video is aligned to the right. So if I have the video as 16:9, both "Center" and "Right" alignment functions in the extension will just make it go _further_ to the right. If I use the "Left" alignment in the extension then it is somewhat centered.

**To Reproduce**
I tried multiple videos in Hulu. I also tried this on both Chrome and Microsoft Edge. It was the same on both and for each movie/tv show I tried. 

**Expected behavior**
Image should be centered and 21:9 should fill width of screen. 

**Screenshots**
I've attached a screenshot with the image supposed to be center aligned. 
![IMG_1802](https://user-images.githubusercontent.com/72991427/96287201-8df0e400-0faf-11eb-9ece-20672cc955d8.jpg)

I also have one where the cropping mode is set to 21:9 rather than 16:9
![IMG_1803](https://user-images.githubusercontent.com/72991427/96287345-ca244480-0faf-11eb-8406-66667a2e596c.jpg)

**Browser and OS**
 * Browser/browser version: Google Chrome 86.0.4240.75 & Microsoft Edge 86.0.622.38
 * Operating system: Windows 10 64-bit
 * Ultrawidify version: 4.4.9

**Additional info**
Any other things you want to say.

**Comment by tamius-han** [comment]
Turns out that Hulu needs some special CSS to get things working.

The fix is known and is due to be released with the next update, which is progressing more slowly than intended.

In the meantime, here's what you need to do to fix this:

1. Click the extension popup
2. Go to 'Advanced settings'
3. scroll to the bottom
4. Paste this in the bottom-most "additional CSS" box:

`margin-left: 0px !important; object-fit: initial !important;`

![slika](https://user-images.githubusercontent.com/12505802/96628371-6fbe1780-1312-11eb-8f54-06dfc08968c9.png)

If there are any problems, remove the `object-fit` part and everything after it.

**Comment by tamius-han** [comment]
Yay, review times on Chrome Web Store are several _weeks_ so you're in for a bit of wait. Still gonna close this.

~~Mind, still better than Opera. 7 months and counting.~~
