### ISSUE TITLE
Is this supposed to be working for partially-ultrawide videos?

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#113]
Just watched a video on Wakanim on Firefox where it's only ultrawide for a minute: https://www.wakanim.tv/de/v2/catalogue/episode/24715/assault-lily-bouquet-staffel-1-folge-1-omu

Ultrawidify didn't detect it, but I'm not sure that's because Wakanim is simply not supported or it's because the video is only partially ultrawide.

![image](https://user-images.githubusercontent.com/3396686/96491256-46ce5180-1242-11eb-860d-8863fdca19ba.png)

![image](https://user-images.githubusercontent.com/3396686/96491327-5f3e6c00-1242-11eb-82e2-87deccb1b309.png)

**Comment by tamius-han** [comment]
Ultrawidify should detect videos that switch between multiple aspect ratios, which means there's two possible options:

* Ultrawidify doesn't work on that site.
* Site utilizes DRM. While this is a sorta-advertised feature in Firefox, it's rather unreliable thanks to the hoops required to jump through.

If manually setting aspect ratio doesn't work, then it's the former. If it's the former, [you can fix that](https://github.com/tamius-han/ultrawidify/wiki/Fixing-site-incompatibilites-('Advanced-settings')) (as through the magic of geo-locking, I am unable to).

**Comment by saschanaz** [comment]
Clicking Video Settings->Crop mode buttons doesn't do anything (which looks like another bug) but shortcuts do work (only when in fullscreen, is this expected?). Wakanim indeed seems to use DRM encryption.

> it's rather unreliable thanks to the hoops required to jump through.

Is there a way to make it more reliable by some manual settings?

**Comment by tamius-han** [comment]
> Clicking Video Settings->Crop mode buttons doesn't do anything (which looks like another bug) but shortcuts do work (only when in fullscreen, is this expected?)

So it's the option A, then ("bad" CSS on the site preventing extension from working). 

Just for shits and giggles — try putting `margin: 0 !important` into `Advanced settings -> Video detection settings -> Additional CSS` box and see if it fixes the problem. Otherwise: [fixing site incompatibilities](https://github.com/tamius-han/ultrawidify/wiki/Fixing-site-incompatibilites-('Advanced-settings')). (TL;DR: Advanced settings -> player detection settings -> try playing with parent node index thing a bit). 

> Edit: It seems captureVisibleTab is not used, which API are you using?

`canvas.drawWindow()` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWindow)), which is honestly the most convenient way to do this kind of thing. TIL it's deprecated now. Too bad, really. And if memory serves me right, it only draws the contents of the `<video>` tag, too.

Oh well, one of these days I might re-attempt to use webgl to do aspect ratio detection, so moving everything to `captureVisibleTab` might get a go, too.

**Comment by saschanaz** [comment]
`#jwplayer-container` did the work, clicking the ratio buttons now affects the video size. 👍

BTW, `encryption=cenc` in network log makes me believe it's using DRM. Unfortunately the fallback for DRM doesn't seem to work as clicking Auto does not do anything.

![image](https://user-images.githubusercontent.com/3396686/96798906-2c42d680-1402-11eb-9798-47e221974143.png)

Is there something I can try more?

**Comment by saschanaz** [comment]
BTW I found the reason `drawWindow` is being deprecated is because it's synchronous: https://bugzilla.mozilla.org/show_bug.cgi?id=1664444

**Comment by saschanaz** [comment]
Thank you! ❤
