### ISSUE TITLE
21:9 Not working [BECAUSE EDGE IS FUCKING IRREDEEMABLE GARBAGE, USE CHROME, thx, —Tam]

### ISSUE THREAD

**Issue by duaragha** [tamius-han/ultrawidify#117]
I have the shortcut set to D, but whenever I click it Netflix does something weird. It lifts the video up, (making the bottom black) and it doesn't even remove the black bars into the side
![2020-10-28 (8)_LI](https://user-images.githubusercontent.com/47542632/97495723-5b939f00-193e-11eb-8770-142425689caf.jpg)
 (look at screenshot provided)

**Comment by Phoenomenal** [comment]
duaragha ,  What browser you use ?

On New Microsoft Edge Netflix is broken  and every video with wider than 16:9 aspect ratio open just like this (without any extension)  The only thing possible there is to lower the video with extensions to make it fit the center of the screen but it have black bars on all 4 sides of the screen then.  I believe chrome have  some similar problem because they use  the same chromium engine. 

There is no  fix to this as of now,  all we have to do is wait and use Netflix app instead.

**Comment by tamius-han** [comment]
Quick question. With extension disabled, is the netflix video cropped
correctly (-ish)?

V V sre., 4. nov. 2020 ob 13:10 je oseba Phoenomenal <
notifications@github.com> napisala:

**Comment by Phoenomenal** [comment]
No,  thats how all wideos wider than 16:9  in Netflix using Microsoft Edge browser look without any 21:9  extension.   This problem only in Chromium Edge since v. 83....      

![Microsoft Edge without extension](https://user-images.githubusercontent.com/68902338/98114142-dd8f4500-1eb5-11eb-8719-19f6391f9db7.jpg)

**Comment by Phoenomenal** [comment]
Update.   Was testing Netflix + ultrawidify on Chrome.   Without extension all videos (wider than 16:9 )  play to fill the screen vertically as it should be.   With the extension you can stretch and crop however you want without any problem .  So its not the chromium browser problem and only Edge.    

On Edge on the other hand even 16:9  and 4:3  videos  dont crop/stretch  with the ultrawidify.  But they at least load normally without the ultrawidify to fill fullscreen vertically (only black bars by the sides on ultrawide monitors  as it should be on 16:9  and 4:3 videos)  On the other hand videos with wider than 16:9 aspect ratio  like in the picture above load like this without extension and there is no way to make them fill the screen with or without extensions.  I tried others similar to ultrawidify extensions and the result was the same.  

Its a real shame because Edge is the only browser to support 4k.

**Comment by duaragha** [comment]
yeah i realized i was getting this problem cause of edge, I tried using chrome and Netflix was working fine there. i don't really keep chrome downloaded on my computer so it will be annoying to have a separate browser just for Netflix, but meh whatever. hopefully, this extension manages to work with edge sooner or later

**Comment by duaragha** [comment]
> duaragha , What browser you use ?
> 
> On New Microsoft Edge Netflix is broken and every video with wider than 16:9 aspect ratio open just like this (without any extension) The only thing possible there is to lower the video with extensions to make it fit the center of the screen but it have black bars on all 4 sides of the screen then. I believe chrome have some similar problem because they use the same chromium engine.
> 
> There is no fix to this as of now, all we have to do is wait and use Netflix app instead.

btw i tried using the app, and i still got the same error (plus the only reason i don't wanna use the app is cause i cant speed it up (only on browser or phone)

**Comment by tamius-han** [comment]
Heads up: Chrome got a very similar issue with 4.5.0.

**In chrome, this issue is mostly fixed by pressing 'reset' and then 21:9.**

The issue only appears on videos with `style="height: {anything other than 100}%`

This does not seem to be the same issue as described here, since it's very specific to Netflix-specific exceptions in default config.

**Comment by tamius-han** [comment]
Good news everyone, I've found the reason for the bug.

# Microsoft Edge is BAD and everyone developing it should feel bad

And I shouldn't be this salty because pouncing all over github issues over things not working like a 7 year old is not very professional but I literally just lost two full days' worth of my free time to this shit.

## But honestly consider using Chrome or reporting an issue with Microsoft

Here's what I need you to do:

* Open up Netflix with extension disabled.
* Load up a decent movie that's 21:9 (you know at least one example if you're reading this, but for the sake of completeness here's few examples in no particular order: _Edge of Tomorrow_, _Warcraft_ (if you still have it & don't @ me), _World War Z_ or _Lord of the Rings_)
* As you have noticed as far back as a month ago, the video will be offset
* Click this:

![slika](https://user-images.githubusercontent.com/12505802/102417170-7956b980-3ffb-11eb-91b0-e92f8fb04d74.png)

* Enter this pasta:

```
Video is not scaled correctly when <video> has any of the following styles:

* height: [anything bigger than 100%]
* transform: scale(x)

Where 'x' is any number greater than 1. In such cases, the <video> element will be resized, but the video inside the video element will remain at the initial size, resulting in black borders along the bottom and the right side of the video (the video will appear to be aligned to the top-left of the <video> element)
```

Into the textbox you get:
![slika](https://user-images.githubusercontent.com/12505802/102418159-7b217c80-3ffd-11eb-8d6f-579810779973.png)

Providing e-mail is optional.

In the mean time, I am pulling the extension from Microsoft store. Workaround _is_ possible (add a `<div>` around the `<video>`, style that `<div>` instead of the video and force video to be 100% of the parent div width and parent div height), but it's the kind of thing that would ruin my holiday.

**Comment by tamius-han** [comment]
Another thing, to follow up with the previous comment — I've said that:

> Workaround is possible (add a <div> around the <video>, style that <div> instead of the video and force video to be 100% of the parent div width and parent div height), but it's the kind of thing that would ruin my holiday.

in my previous comment, because it seemed like it could work and would be somewhat consistent with observed behaviour. I've tried to implement a proof-of-concept workaround because it would bug me if I didn't try that for shits and giggles. But as it turns out, this way doesn't work either. Even if you set the immediate parent to appropriate height and keep the `<video>` tag at height: 100%, things don't work.

Which means that:
* there is no workaround
* this issue is fundamentally unfixable

Closing this issue. I am open to porting Ultrawidify to Edge Chromium once Microsoft fixes their shit browser.

**Comment by tamius-han** [comment]
So we've got an update. TL;DR: as of **today**, edge works for me.



Here's a few more "fun" things to say about this issue.

For the past 14ish days, I've been getting 'Edge works now' messages on reddit and here. Mostly chalked them up to false reports and cannot reproduce, because despite pretty much exclusively using Windows for the past three weeks (HZD <3, work </3), the issue has kept popping up for me as late as this past friday, possibly saturday morning (but I don't remember).

The fun part? According to the UA string, Edge didn't get any updates. 

So this was probably a Windows issue.

Except that I recall no updates when doing my almost daily reboots (courtesy of dual booting), but then again ... I suppose not all windows updates require a reboot.
