### ISSUE TITLE
[BUG] Flicks on change ratio / size of video 

### ISSUE THREAD

**Issue by BlackYuzia** [tamius-han/ultrawidify#123]
### Description

Trouble on site: **youtube**.
Video with trouble: **https://youtu.be/HZvizyfk9WM**
Short description: **When video change ratio (from 16:9 to 4:3 then back etc) I would get "lags" or "freezes". You can get the same effect if you just watch this video. 

### To Reproduce
Open video
Enable hybrid mode (I mean **stretch mode**)
Enable extension
Wait until you get freezes or moves video up/down or left/right a bit when ratio would be change.

**You should watch video from the start!**

### Expected behavior
What do you think should happen instead?

### Screenshots

Note: Screenshots **WITHOUT** enabled extension. 

Owners of video make a few ratio of size. Like:
Here wide:
![image](https://user-images.githubusercontent.com/25010528/101989806-872ed680-3cab-11eb-8122-73cfd17ddf39.png)
Here is short:
![image](https://user-images.githubusercontent.com/25010528/101989813-92820200-3cab-11eb-8a13-23acd6cd3149.png)
Then again wide:
![image](https://user-images.githubusercontent.com/25010528/101989834-aaf21c80-3cab-11eb-859b-0a74c49bae5c.png)

This can change/switch very fast. This is trouble why I get freezes / lags what I saw every time when video would be change (size) (like extension detect what video have small size then change it. Video change size, extension spend some time for detect this change again, then resize video and this would retry again and again)

### Browser and OS
 * Browser/browser version: **Chrome 87.0.4280.88**
 * Operating system: **Win 7**
 * Ultrawidify version: **4.4.10.1**

### Additional info
I would get info did you/we can fix that flicks up/down (left/right)?

**Comment by tamius-han** [comment]
> When video change ratio (from 16:9 to 4:3 then back etc) I would get "lags" or "freezes".

Just to clarify: by 'lags and freezes', you mean that the video will get stuck on a frame from a few moments (as opposed to "video plays normally, but aspect ratio detection takes some time to happen"), right?

Because the video playback works for me fine (other than the fact that aspect ratio changes aren't detected immediately, but that's a design decision). 

Can you tell me what CPU you're running?

Because I've done all optimizations I'm smart enough to make, so the only ways of fixing freezes and laginess is to:

* don't use autodetection.
* go to extension settings, 'autodetection' tab, and do any combination of the following:
 * Decrease autodetection frequency (the first slider). The extension will check for changes less often and will therefore freeze less often — but it'll now take longer for extension to detect aspect ratio change
 * Scroll to 'sampling options' and decrease 'Sample width' to 426 (or 256) and the _bottom_ 'static rows' to 240 (or 144). This may make aspect ratio detection a bit less accurate and result in slight overcrop or undercrop. 
 * Scroll to 'Blackbar' and set 'Gradient detection' option to disabled.
 * Scroll to 'Sampling options' and decrease 'static sample columns' number. You should really do all the other options first, though.

(Note that settings page wasn't tested in a while, so it's possible some bugs popped up there)

**Comment by BlackYuzia** [comment]
Nope. By lags and freezes I mean side effects by "not detected immediately". So, side effect this is a bit pause before video would change size ratio by extension. So, I saw this pause and this bad.

**Comment by tamius-han** [comment]
Yeah, this is by design, as running autodetection at 30/60 FPS used to casue RAM usage to explode due to reasons beyond my control.

You can increase the frequency in the settings, but if your memory usage starts suddenly going into multuple gigabytes over what you'd expect it to be ... this is the reason.

Tick rate of 10ms should be okay, though it may still take a frame or two before extension detects the change because the extension can only react to what's being displayed on screen.

**Comment by BlackYuzia** [comment]
@tamius-han did you can use **mutationObserver** for detect changes?

**Comment by BlackYuzia** [comment]
Note: I "fix" this pauses (maybe right name this is a video "shakes", idk) by set frequency to value 11. :eyes:

PS: This pauses didn't expire but now not so big / long

**Comment by tamius-han** [comment]
> did you can use MutationObserver for detect changes?

Not gonna work.

* MutationObserver only triggers after the change happens IIRC (and is otherwise pretty janky, too)
* aspect ratio changes in the video doesn't trigger mutation observer. The size of the video element and the file both remain constant.

**Comment by BlackYuzia** [comment]
Okey, I close this issue by mark as "fixed" by change settings  https://github.com/tamius-han/ultrawidify/issues/123#issuecomment-744009756
