### ISSUE TITLE
edge is working again, remove the anoying banner

### ISSUE THREAD

**Issue by regisbsb** [tamius-han/ultrawidify#129]
as it says on the tin

**Comment by regisbsb** [comment]
@tamius-han

**Comment by tamius-han** [comment]
Edge is, in fact, not working.

![IMG_20201227_214317](https://user-images.githubusercontent.com/12505802/103179480-de789d80-488c-11eb-8655-26090af54fb9.jpg)

**Comment by regisbsb** [comment]
I've tested on my Edge Chromeium and it's fine. Netflix,  youtube,  etc. At least a global option to disable pop-up.

**Comment by tamius-han** [comment]
It most certainly doesn't work on netflix (and I am, according to the internet, on the latest edge version. Speaking of that — the popup also asks you to include the UA string, which is missing from this report). 

It works _fine_ on youtube, but that's why you shouldn't be getting the popup on youtube, twitch, reddit, facebook, other sites that don't do DRM.

> At least a global option to disable pop-up.

Lots of 'maybe' and after the holidays.

(It doesn't seem I can modify settings from the popup the nice way, which is why showing and hiding the popup is currently piggibacking off autodetection, i.e. that's the reason you need to disable autodetection for a site in order to also hide the popup)

**Comment by TechnoStone** [comment]
![image](https://user-images.githubusercontent.com/26044948/104618286-8c61b580-569d-11eb-8155-2a03f0166ee5.png)
Hm, Edge team answered for this.
Idk how's all, but for me all works correctly

**Comment by tamius-han** [comment]
How come _I_ don't get the email? Not fair, MS Edge team. Is it because I bitched about that big time on my blog?

Anyway, to give this update in this issue as well:

* This issue was fixed by Sunday for me (and it very obviously wasn't fixed as late as Saturday morning)
* The version of the addon that removes the popup was live monday-ish on Chrome Web Store. Tuesday-ish, Ultrawidify has passed MS Edge review and is now also available in the Edge Addons store.
 
 Speaking of which: if you're using Edge, consider installing Ultrawidify from [Edge Addons](https://microsoftedge.microsoft.com/addons/detail/ultrawidify/lmpgpgechmkkkehkihpiddbcbgibokbi) store.

* (There's also been another update that fixes few other things — most notably, DRM detection (meaning 'autodetection is not supported on this site' popup should no longer show on sites where autodetection can run) and hybrid stretch. Freshly cleared the review both in Edge and Chrome)
