### ISSUE TITLE
32:9 fit to width does not allow pan

### ISSUE THREAD

**Issue by arne182** [tamius-han/ultrawidify#135]
**Describe the bug**
When using fit to width neither pan nor the hotkey for pan allows the image to pan up and down

**To Reproduce**
press w and try with shift to move the image

**Expected behavior**
Shift should work to move image up and down

**Screenshots**
A picture is worth a thousand words. If Ultrawidify scales a video in an improper way, please include a screenshot of that.

**Browser and OS**
 * Browser/browser version: Chrome 80
 * Operating system: Windows 10
 * Ultrawidify version: 4.5.3.1

**Additional info**
Thanks for the amazing work

**Comment by tamius-han** [comment]
At the moment, none of the zoom levels should allow panning. That has been taken out some time ago because there's been some issues — namely, it being completely broken.

While I do have plans to re-enable that (+ step-by-step zoom) at some point, it's gonna take a while for that. Mainly because porting my extension to typescript made me realize my code is a fair bit shittier than I thought it was.

**Comment by tamius-han** [comment]
Panning should be available again, as of v5.0.0.
