### ISSUE TITLE
Manual zoom doesn't work

### ISSUE THREAD

**Issue by ShadowMaster85** [tamius-han/ultrawidify#138]
The zoom shortcut keys Z and U are not working so is impossible to zoom the video on any site, this same problem is also present in all of the previous versions of Ultrawidify extension of the last months.

Actually I am using the latest version of Opera 74.0.3911.218 Official Portable with the latest Ultrawidify extension version 4.5.3.1 available on the Chrome store.

To reproduce simply open a site with a video and try to zoom the video with the shortcut keys Z and U.

Expected behavior the zoom keys Z and U should be work as described.

 * Browser/browser version: Opera 74.0.3911.218 Official Portable
 * Operating system: Windows 10 Home 1709
 * Ultrawidify version: 4.5.3.1 from Chrome store

I tryed some months ago this same extension with Firefox and the shortcut keys Z and U were working as expected.

**Comment by tamius-han** [comment]
Thanks for reporting.

Shortcuts Z and U have been disabled a while back for the time being, as they started to interfere with autodetection. Fit to width, 21:9, 18:9 (and autodetection on sites _not_ utilizing DRM) should still work.

**Fix when?**

No ETA, but given the amount of problems I discovered recently when doing a sorta minor rewrite I think I might be able to have a fix in time for the next version.

Currently, the biggest issue preventing the next version from coming out is ... well, popup broke again, for some weird reason. And issues with the popup are always the least fun and easy to fix.

**Comment by ShadowMaster85** [comment]
How can i download the last previous version of Ultrawidify wich support the Zoom function with the shortcut keys Z and U ?
Thanks.

**Comment by tamius-han** [comment]
Sorry for falling off the face of the world again.

* You can't. IIRC Chrome Web Store doesn't allow you to get old versions of the extension
* You _may_ have some luck getting an older [nightly version](https://stuff.lionsarch.tamius.net/ultrawidify) and run the extension in developer mode.

Note that 'nightly' versions are called 'nightly' because they get built at like 4 AM if there's been any changes to the master branch (and if jenkins is up, which isn't a given) ***no matter what.***
