### ISSUE TITLE
[Firefox] Video goes tiny to the top left corner after exiting fullscreen on YouTube

### ISSUE THREAD

**Issue by nincsneve** [tamius-han/ultrawidify#140]
**Describe the bug**
Normal, 16:9 video, goes really tiny after exiting full screen on YouTube. Window size of Firefox is definitely matters, I put the details (results) into the next chapter.

**To Reproduce**
Get one 16:9 video with black bars and another one without black bars. It doesn't matter if the video is playing or not (however I executed the tests while video was playing)
1. Click on full screen
2. Click on exit full screen
3. Video gets tiny

**Results**
1. Firefox maximized: No issue with either of the videos (no screenshots either)
2. Firefox is just big enough to fit the video frame (699x639): video with black bars gets tiny, video **without** black bars behaves as expected and fills the frame
3. Firefox with weird window size (1202x1400): both test videos have the issue

Reproduction rate is 99%

**Expected behavior**
Video fills the frame instead of turning into very small

**Screenshots**
Test 2 (Firefox window 699x639)
Video with black bars (failed)
![image](https://user-images.githubusercontent.com/81524654/112760775-74d96e00-8ff8-11eb-8466-11c841984275.png)

Video without black bars (passed)
![image](https://user-images.githubusercontent.com/81524654/112760724-583d3600-8ff8-11eb-930d-7ab970e3f5d4.png)

Test 3 (Firefox window 1202x1400):
Video with black bars (failed)
![image](https://user-images.githubusercontent.com/81524654/112760951-224c8180-8ff9-11eb-9199-bed5c841ca7e.png)

Video without black bars (failed)
![image](https://user-images.githubusercontent.com/81524654/112760989-460fc780-8ff9-11eb-8940-e580ccdc5139.png)

**Browser and OS**
 * Browser/browser version: Firefox 87.0 (64 bit)
 * Operating system: Windows 10 Pro (64 bit), OS build: 19041.867, Experience: WFEP 120.2212.551.0
 * Ultrawidify version: 4.5.3

**Additional info**
There were rare cases when video jumped back to normal size, but it went tiny first. That's why the reproduction rate is not 100%.
Maybe a timing issue? I have an AMD Ryzen 5 3600 CPU, only Firefox ran when I executed the tests.

**Comment by tamius-han** [comment]
> Maybe a timing issue? I have an AMD Ryzen 5 3600 CPU

This appears to be the case so far. Current theory is that on newer, faster processors, observers trigger before the actual elements change in size, given that it doesn't happen to me (on a 2700X+linux) almost ever. 

And the issue goes away the moment I try to log it.

Workaround: resetting aspect ratio (and/or re-starting autodetection) seems to correct the issue for me.

**Comment by nincsneve** [comment]
The issue disappeared with version 5.0.0.
Whether it was intentional or not, thx the great work! You can close this one :)

**Comment by tamius-han** [comment]
Yeah, 5.0.0 had a fix for this issue. Thanks for the follow-up. I've missed this issue when cleaning up fixed problems yesterday. 

I've done this in the chrome version of this issue (#133 , might as well do it here as well.

### Technical details for people who want technical details.

Long story short: 

1. apparently you can actually have dimensions of an element change without MutationObserver getting triggered (I've actually noticed that on reddit. Youtube changes style attribute of <video> element when you resize the page, so MutationObserver triggers always. Reddit slaps a class with `width: 100%; height: auto` to the video and calls it a day, which doesn't trigger MutationObserver if you resize the window by opening devtools while in fullscreen)
2. as already observed: apparently mutation observer triggers _before_ the changes applied to the HTML element take place — something that isn't a problem on most CPUs because usually the browser applied changes to the element fast enough, but then CPUs got faster while browsers (and prolly this extension) got more optimized ...

Anyway, solution: ditched MutationObserver for ResizeObserver.

This is a rather new-ish option that was considered very "experimental don't use for reals" back when I was implementing observers. If you ask typescript maintainers as of relatively recently, this is still the case: I've heard when typescript developers play uno, there's an 'add support for ResizeObservers or draw 25' card in the deck. Legends say that when senior devs get that card played against them, they draw not only 25, but the entire damn deck.

~~Okay that was a belated March 32rd joke~~

Anyway, went ahead and checked the compatibility. Turns out that all major browsers have been supporting ResizeObserver for a year or two now so ... I don't suppose there's many people using browsers that are one or two years out of date.

Seems to work like a charm.
