### ISSUE TITLE
Settings don't get saved from popup (+ settings page fucky wucky)

### ISSUE THREAD

**Issue by Tigornmagnus** [tamius-han/ultrawidify#142]
**Describe the bug**
Since the update yesterday Ultrawidify basically stopped working entirely.
The autodetection and cropping works in YT (haven't tested anything else) but the hotkeys do not work anymore. Changing any setting in the Quick Settings Menu (i.e. disabling it for a website like Reddit, changing stretch or crop mode, basically all the Extension/Site/Video/Advanced Settings) also doesn't work since it resets everything upon exiting the Quick Settings Menu.
The Extension settings Page also doesn't open and displays a blank screen.

**Expected behavior**
Changed settings should be saved and kept after closing the settings Window/Hotkeys should work/the settings Page should not show a blank screen.

**Browser and OS**
 * Browser/browser version: Firefox 87.0
 * Operating system: Win 10/completely up to date
 * Ultrawidify version: 5.0.0

**Additional info**
Version 4.5.3 is working as expected so I'm pretty sure something is wrong with the new update.

**Comment by rinakoc** [comment]
the new version works for me however it doesnt save/remember the settings 
in other words i have to click/press keybind for crop/stretching on every video.
right now i am using the 4.5.3 version since i find it annoying to manually use the extension on every video

**Comment by tamius-han** [comment]
I swear this isn't april fools.

Basically what's going on: 
* When the extension starts, it checks whether an update happened.
* Back when 4.0.0 was brand new, the settings format changed a lot. I decided that instead of migrating the settings from 3.x, I'll just reset them to defaults of 4.0.0.
* The settings got reset if the first number of the version was anything other than 4.

Thanks a lot, past me.

Fix for firefox will be up rather quickly. Chrome et. al. is gonna be a bit more problematic.

&nbsp;

&nbsp;

&nbsp;

Also keyboard shortcuts work fine for me?

**Comment by tamius-han** [comment]
This should be fixed now.
