### ISSUE TITLE
settings page link not working on the quick settings popup 

### ISSUE THREAD

**Issue by markusd1984** [tamius-han/ultrawidify#147]
when clicking the extension icon, under Video Settings there is a hyperlink to "the settings page" which doesn't open anything, but pasting the link into a tab manually works `chrome-extension://dndehlekllfkaijdlokmmicgnlanfjbi/popup/popup.html#`.

> You can change or add additional aspect ratios on the settings page (in 'actions&shortcuts' menu).

Chrome Version 89.0.4389.114 (Official Build) (64-bit)

Btw. could be quite useful to also have a short cut on the "Quick settings" page to the Options page that one only can get to via right click on the extension > Options.

chrome-extension://dndehlekllfkaijdlokmmicgnlanfjbi/options/options.html

**Comment by tamius-han** [comment]
So it turns out that:

* browserDetection based on checking whether `browser` is defined or not isn't going to work if `webextension-polyfill` adds `browser` object to chromium-based browsers
* webextension-polyfill doesn't include the `openSettingsPage()` method, even though it's been available in Firefox for about as long as this extension has existed

Who would have known.
