### ISSUE TITLE
Is it possible to unstretch, for 21:9 being presented as 16:9 (needs letterboxes but missing them)?

### ISSUE THREAD

**Issue by IvanExpert** [tamius-han/ultrawidify#153]
I was very excited to find ultrawidify, because I was watching a streaming movie that I think was supposed to be 21:9, but incorrectly being presented as 16:9 without letterboxes, so everyone was vertically stretched.

The "Basic" option in stretch got me a little closer to what I wanted, though it wasn't a full correction (things were still somewhat vertically stretched), and it cut off the sides rather than letterboxing.

I tried going into all the settings and couldn't figure out how to add aspect ratios, so I went into Super Advanced and tried to modify the "Stretch Source to 16:9" stretch by changing customArg to 2.35, but all that did was make things even taller and narrower. I played with it a little, like trying negative numbers (that, interestingly, reversed the image horizontally), and numbers between 0 and 1 (which made things super tall and narrow, which I didn't really understand).

Unfortunately, the streaming source is live, so I can't give to to you to reproduce on demand. But in general, to reproduce, if we had a proper looking 16:9 movie, and could squash it vertically with a settable number by adding letterboxes (not sideboxes), so everyone would appear wide rather than tall, that would have the intended effect. It would be great to be able to arbitrarily stretch or unstretch, with or without sideboxes or letterboxes, to accomodate every kind of screwed up video.

But, super cool extension! Let me know if I can help answer any questions.

Using Chrome (current) on macOS 11.3.1.

**Comment by tamius-han** [comment]
In theory, the extension should already do that (though stretching the video won't add letterbox _ever_ — instead, left and right edges would get cropped away). 

In practice, you've stumbled across the bug. Thanks for reporting.

# Theory 

Yes-ish, and you've got roughly the right idea on how to do it. `Stretch source` options (aka `stretch: fixed (src)` or `arg: 5` for `set-stretch`, if you're doing advanced settings) prolly aren't the best name, but they basically say:

* see this video?
* I know for a fact that video is in [aspect ratio]
* stretch it

~~There's actually two different ways of stretching to a different aspect ratio that mildly differ in how they work, but you want this one.~~

It's worth noting that because _reasons_, the extension isn't going to add any letterbox to the video. In theory, if you tried to stretch a video to an aspect ratio than your monitor, the edges of the video would get cropped away ... but it's okay (tm) because you can unzoom on your own. You could technically even make an action that does both.

~~There's actually some reasons why, in retrospect, this totally isn't okay, but this feature was pitched in #81 as a "yeah I've got a 4:3 video that some uncultured swine stretched to 16:9, how can I undo that?" and it was implemented with this mindset, too.~~
 
# Practice

* When extension determines how to stretch and crop, it takes into account both the video dimensions, and the dimensions of the player the video is playing in. 
* If the aspect ratio of the (stretched) video is wider than the aspect ratio of the player element, the extension will, for some reason, apply stretch along the wrong axis

**Comment by tamius-han** [comment]
Think I've sorta-fixed this problem.

* Yes, the incorrect stretch should no longer happen.
* If the aspect ratio is too wide, edges will clip. Use zoom keys to zoom in/zoom out if that happens.

New version should be up later this week.
