### ISSUE TITLE
Zoom In not working properly with youtube

### ISSUE THREAD

**Issue by kh-nguyen** [tamius-han/ultrawidify#159]
1-2 weeks ago, I was still able to use Zoom In function at full screen while I was watching youtube. Now, i'm not sure what changes have been made that the function is not working anymore. I can still zoom out at fullscreen but the zoom in is maxed at fullscreen and cannot be zoomed in more that what is seen on the screen at fullscreen. I'm using Chrome with ultrawidify 5.0.5

Is the problem because of recent changes to the ultrawidify or because of my computer's problem?

**Comment by tamius-han** [comment]
>  is maxed at fullscreen and cannot be zoomed in more that what is seen on the screen at fullscreen.

Please define "zoomed in more than what is seen on the screen at fullscreen" in more detail.

In Chrome (and Edge and basically everything that's Chromium-based), Ultrawidify _does_ limit zoom while in proper full screen. This functionality has been present — to a varying degree — since February and can be, as of late march/early april, be toggled off in advanced settings. It's a lil bit weird that it worked two weeks ago, because it shouldn't. 

# The reason for zoom limitations

Some time around Jan 15, 2021 (according to Chrome Web Store reviews), Chrome caught a bug that basically broke each and every extension for fixing 21:9 videos on a wide variety of hardware. [Bug report with video demo](https://bugs.chromium.org/p/chromium/issues/detail?id=1199871)

The only way to avoid this bug is to disable zooming past a certain point (not that this would change anything, since that bug would prevent you from zooming in full screen _anyway_).

Not everyone is affected by this bug, though, which is why the extension allows you to disable this limitation.

# Disabling the mitigation

You'll want to uncheck the 'limit zoom' checkbox (and you'll need to do some scrolling to reach this option):

![image](https://user-images.githubusercontent.com/12505802/124894794-40545580-dfdc-11eb-81fe-eba5090d1b30.png)

# Help my video gets stretched incorrectly when I zoom (and zoom still doesn't work)

If that happens, you'll have to run Chrome with `--disable-direct-composition-video-overlays`. This fixes the problem.

**Comment by kh-nguyen** [comment]
Thanks for the quick response. I can make the zoom in work with Chrome in fullscreen again by running chrome with --disable-direct-composition-video-overlays and disabling 'Limit zoom' in Ultrawidify.
