### ISSUE TITLE
Upscaling Problem On HBO MAX

### ISSUE THREAD

**Issue by arzezio7** [tamius-han/ultrawidify#164]
**Describe the bug**
Picture does not scale correctly on HBO Max. Instead of centered it will go out of bounds.

**To Reproduce**
Pressing any of the shortcut key in the cropping mode

**Expected behavior**
Picture should be upscaled correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/89209677/130097297-9462a7f4-b9f4-45f9-a131-c3fc85385381.png)

**Browser and OS**
 * Browser/browser version: Edge Chromium  92.0.902.73 (x64)
 * Operating system: Windows 10 21H1 build 19043.1165
 * Ultrawidify version: 5.0.6

**Additional info**
Happened on Disney+ Hotstar too but instead of going out of bounds, it will centered but kind of squashed with ta both black bars (top and bottom)

**Comment by tamius-han** [comment]
Unfortunately I don't have HBO Max (nor is it available in my country), so I can't test things by myself.

That being said, try going to _Advanced settings_, check the _Manually specify the player_ checkbox and try increasing the number.  Click save, close the popup, reload page.
![slika](https://user-images.githubusercontent.com/12505802/130135883-6ee29784-b727-48a8-bece-87a410364be9.png)
If you see a different text box, click _use basic options_ link.
If it doesn't work by the time you reach number 10, then this approach probably isn't going to work. Instead, the page will probably require some additional CSS to be written by someone. Since I don't have access to HBO Max, I am looking for help on this one.


> Happened on Disney+ Hotstar too but instead of going out of bounds, it will centered but kind of squashed with ta both black bars (top and bottom)

You mean kinda like this?
![slika](https://user-images.githubusercontent.com/12505802/130120367-72f9c8be-0749-4bbe-8ec3-826cac00ffb7.png)

That's a problem with all Chromium-based browsers, Edge included. `edge://flags`, search for `Choose ANGLE graphics backend`, choose _OpenGL_ or _D3D9_. 

[More info](https://stuff.tamius.net/sacred-texts/2021/08/19/ultrawidify-and-chrome-2021-edition-episode-2/)
