### ISSUE TITLE
Can colored paddings be cropped?

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#173]
![image](https://user-images.githubusercontent.com/3396686/145647692-9a8385d6-9525-4592-b411-a96a4fafd325.png)

https://www.youtube.com/watch?v=fzRWpcvPJYo

For now I can just press X to force 18:9 cropping, but would be great if it can be automated too.

**Comment by tamius-han** [comment]
No, automated detection can't detect colored paddings at present ... and it probably won't at least the near to mid term future, since checking for non-black pixels is a quick and easy way this extension uses to determine how much resources to waste processing a frame. (That, and some other assumptions also rely on the letterboxing being black)
