### ISSUE TITLE
audio issue (crackling sound in some youtube videos)

### ISSUE THREAD

**Issue by 24687953** [tamius-han/ultrawidify#178]
crackling sound in certain youtube videos

I have only noticed them in videos from LinusTechTips or sisterchannels
if I disable ultrawidify extension there are no crackling sounds
if i reload the page, restart the browser or my computer the sounds still appear in (i think) exactly the same places

for comparison: https://youtu.be/Npu7jkJk5nM 1:28 to 1:55

windows 10
firefox
ultrawidify
(all up to date versions)

**Comment by tamius-han** [comment]
That's the second or third time I'm hearing about an instance of issue, but I've never managed to reproduce it on any computer I could get my hands on (and while I do notice something that could amount to crackling on the linked video, it seems to be 'unwanted mouth noises¹' ... and I can hear it even on other browsers and places where I don't have ultrawidify installed by default.

Seeing the issue is closed, I'll assume that either:
* you figured as much (even though this option doesn't fit your problem description),
* you figured what the problem was, or
* you stopped caring

If it was either of the first two options, please elaborate further (as this is a 'good to know' kind of thing). 

### Theory & Historical Data

**For what is worth** — in _theory_, Ultrawidify doesn't mess with the sound and therefore shouldn't result in any audio issues. In practice, autodetection does take a fair bit of processing time². This means that in _(a different) theory_, autodetection could block the browser from doing anything else, which would lead to other issues that shouldn't happen in theory.

But in practice, the last time Ultrawidify had an issue with autodetection being unoptimized and taking excessive amounts of time, the problems always appeared in roughly this order:

* video being slightly choppy
* website UI being unresponsive (or taking long time to respond)
* video being big time choppy
* video playback stopping until CPU caught up the work autodetection wanted to do

and nobody reported any audio issues.

————

[1] I am by no means an expert, but the noise in the background sounds like a milder version of the mouth noises I got on tape this weekend when recording a D&D session for a friend.
[2] And the last time I looked at that, most of the time is spent waiting for browser to give me the current video frame ... so it's not something that can be optimized away.

**Comment by 24687953** [comment]
i closed it because the issue just dissapeared from youtube (it has been there for a week or more), and i noticed it happening to spotify in rare instances and I was rather certain that your extension doesnt intend to do any audio things and it happening to spotify led me to believe that it might be my PC that has some kind of problem
on your [1]: there is a very quiet background tune in the background of the YT video, but the crackling always appeared randomly near the same spots (sometimes once, sometimes three times), I tried recording it with loopback, but even tho I thought that there was crackling in the part I recorded, when listening to my recording, there was none
sorry for the rushed sentences and thanks for your time

**Comment by tamius-han** [comment]
Well, thank you for the response, then.
