### ISSUE TITLE
Does not work in YouTube picture-in-picture mode.

### ISSUE THREAD

**Issue by Recnelis0** [tamius-han/ultrawidify#182]
**Describe the bug**
The plug-in does not work in YouTube picture-in-picture mode.

**To Reproduce**
Play any video in YouTube, change its aspect ratio, and then click the "picture-in-picture" button located at the right side of the video when the mouse cursor hovering the video. The pop-up video window goes back to its original aspect ratio.

**Expected behavior**
The pop-up video window in the picture-in-picture mode should maintain the (modified) aspect ratio.

**Screenshots**
Any YouTube video (after aspect ratio changing) playing in picture-in-picture mode would do.

**Browser and OS**
 * Browser/browser version: Firefox 97.0.1 (64-bit)
 * Operating system: Windows 10
 * Ultrawidify version: 5.1.1

**Additional info**
N/A

**Comment by tamius-han** [comment]
Sorry, but this is (to my knowledge) not possible.

Extensions can modify aspect ratio of the video in a couple of ways that all boil down to changing the size of the `<video>` element on the page in one way or another.

As far as I understand, the content of the picture-in-picture (PiP) popup is raw video taken from the inside of the `<video>` tag. The popup, therefore, doesn't contain any HTML, cannot run any javascript, and is immune to CSS — which means Ultrawidify cannot crop/stretch/etc. the video in the popup, either. As far as Ultrawidify (and the website) are concerned, PiP popup is invisible to them, as (from their point of view) Firefox still pretends the video is being displayed on the page itself rather than in the PiP popup.
