### ISSUE TITLE
No video element is detected on disneyplus.com?

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#184]
**Describe the bug**
For Terminator: Dark Fate: https://www.disneyplus.com/ko-kr/movies/terminator-dark-fate/5ACMNhUVNDAq

**To Reproduce**
Opened that link

**Expected behavior**
The video should be cropped

**Screenshots**
![image](https://user-images.githubusercontent.com/3396686/156943697-95f06c49-9522-4525-aeaa-b56126676cba.png)
![image](https://user-images.githubusercontent.com/3396686/156943740-000aea7c-599f-4ddb-8d6a-bf9f8f8a898e.png)

**Browser and OS**
 * Browser/browser version: Firefox 97.0.1
 * Operating system: Windows 11
 * Ultrawidify version: 5.1.1

**Additional info**
No `fuck-you-and-do-what-i-say` (or such) class is added to `.btm-media-client-element`.

Maybe a dupe of #84, dunno...

**Comment by tamius-han** [comment]
Disney+ has been very hit&miss in the past. Apparently it works for some people and not for others. I don't know because it's not even available in my country.

What happens if, while a video is playing, open the console and paste this into it?

```
document.getElementsByTagName('video')
```
I expect something like this:
![image](https://user-images.githubusercontent.com/12505802/157212437-e1472c87-9a22-47d1-8c4e-550c1238b269.png)

In case previous line of code returns nothing, what about:
```
document.getElementsByTagName('canvas')
```

**Comment by saschanaz** [comment]
Fortunately it's a `video` not `canvas`.

```html
<video class="btm-media-client-element fontDefault fontColorWhite fontOpacity100 fontSize32 fontEdgeNone backgroundColorBlack backgroundOpacity75 windowColorWhite windowOpacity0" disablepictureinpicture="" tabindex="-1" src="blob:https://www.disneyplus.com/d6cc808e-a90a-42b9-9143-4889da4f0e8b"></video>
```

**Comment by tamius-han** [comment]
Housekeeping — this _should_ be fixed for a while. cc #211
