### ISSUE TITLE
Cant use anymore 

### ISSUE THREAD

**Issue by bcknee** [tamius-han/ultrawidify#199]
I use it mainly with youtube but tried with AppleTV Disney plus and Hbo Max but all of a sudden now the extension doesn't change anything with the video and if I keep trying it will no longer open and sometimes will just cycle thru different aspect ratio options.  Worked perfect for years not sure what happened I use latest Vivaldi version haven't tried with a different browser yet so that might be the issue considering I don't see anyone else posting about this, hope I can figure out a solution

**Comment by tamius-han** [comment]
Hi,

> but all of a sudden now the extension doesn't change anything with the video and if I keep trying it will no longer open and sometimes will just cycle thru different aspect ratio options. 

Just for clarification, when you say "extension doesn't work," do you mean:
* "autodetection doesnt work," or do you mean:
*  "trying to set aspect ratio manually via keyboard shortcut/from popup does nothing"? 

Autodetection won't work on Disney+ or HBO Max (AppleTV is likely in this bin, too), because those sites (use DRM, which will) actively block you from accessing video with a script. You need to set aspect ratio manually on these sites.

IN ADDITION TO THAT:
Disney+ is some broken ass shit. Some people say it works for them, some people say it doesn't. When I tried to debug it (when I briefly had access to it), I even had the problems detecting video element manually from time to time.

**Comment by bcknee** [comment]
When I try and use any feature auto detection, or when i try and set one manually it doesn't do anything and then the interface stops popping up when I click on the button on the extension bar unless I restart my browser or reinstall the extension sometimes it will start cycling thru aspect ratios used to work flawlessly up until a few days ago

**Comment by bcknee** [comment]
updated vivaldi to latest snapshot and some functionality came back was able to apply 21:9 aspect ratio but the interface keeps disappearing still and wont come back when I click the button will keep testing and report back

**Comment by tamius-han** [comment]
Hi,

do you only get problems when using vivaldi, or do the problems pop up with Chrome or Edge as well?

**Comment by bureau55** [comment]
Hey tamius-han,

first of all, thanks for this great extension and sorry for my possibly bad english, I'm from Germany. I hope I can explain everything clearly.

I think i have the same problem.
Everything works fine for the past few months, but now since a few days the extensenion didn't work like bevor.

In my Chrome browser the extension works until I click on a button in the pop-up menu, whether streching or cropping. Then the menu freezes and I can't click on any button. The menu disappears when i click somewhere else in the browser. After that the menu no longer pop up when i click on the button in the extension bar unless i restart the browser.

The video itself does not stretch but mostly shifts to the left side in full view or nothing happens.

I also deactivated all other extensions to see if they interfered with eatch other, but this didn't help.
I also tried it in the Edge browser, but there i have the same problem and the menu freezes as well.

Then I downloaded and tried it in Firefox and there everything works fine as before without any problems.

So maybe something is wrong with the Chromium based browsers?

P.S.: I used the extension for streching videos on YouTube and Netflix. My Chrome version is 104.0.5112.81 64-Bit

**Comment by bureau55** [comment]
Hey,
I may have found out something interesting.

Also the Ultrawidify options cannot be opened via the button in the extension bar, if you have pressed it before.

But if I go directly to the Ultrawidify options after restarting the browser it will open and I can select "Basic stretch" under "Default stretch mode". After a restart, the videos are stretched as desired again. However the pop-up menu still freezes when you click a button in the pop-op menu and the video slides to the left. But I have found out that the menu reappears between 40 seconds to 2 minutes and then resets everything to "Basic stretch".

If I set "Default stretch mode" to "Don't stretch" and click on the pop-up menu, it freezes as well. But it also reappears between 40 seconds and 2 minutes and sometimes adopts the desired setting for the video.

**Comment by bcknee** [comment]
I have noticed that same thing and that's how I have been using it I wonder
what broke the menu, are you using Vivaldi too or is it disappearing on all
chromium browsers? I meant to test on another but found the workaround

**Comment by Hichem47** [comment]
Same, I need to wait 2 minutes every time, do you think dev team will make update or do you have any alternative on Microsoft edge ? thanks for help

**Comment by tamius-han** [comment]
The dev team:
* had a few updates in the past two weeks so far, because different groups of people are having different problems
* is currently on vacation in Germany — a land where an affluent München suburb only gets you a GPRS signal (aka "forget about internet"). Returning back home this weekend.

I'd really appreciate if you could please export your extension settings (chrome://extensions, then find ultrawidify, click 'details', click 'extension settings' on the extension settings screen). On the extension settings page, click 'export settings' button. Github doesn't like `.json` files, so pleasre save it as `.json.txt`. I suspect these issues have something to do with the settings, as I cannot reproduce the problem.

![is this how you do images in markdown? I'm doing this from my email app](https://user-images.githubusercontent.com/12505802/179395814-c8aaab24-385f-43c3-9a0a-722e55e6ff5d.png)

Thanks in advance.

**Comment by tamius-han** [comment]
Notes to self:

* Appears to be a Chrome/Edge + **Windows** specific issue

**Comment by tamius-han** [comment]
Update coming preemtively to Firefox today, Chrome soon, it could take about a week to clear review for Edge.

# Technical stuff

In the background, Ultrawidify keeps track of all pages with videos on them. It did so by keeping an array of tabs that have videos in them. Some (most) actions get sent to all tabs (and then Ultrawidify figures out whether the action is relevant for each tab inside said tab). 

Tab ID was used to determine where in the array the data for tabs were stored. Usually that's not a problem, because you'd have to have _really a lot_ of tabs open before there'd be a problem.

It appears that recently, Chromium-based browsers on Windows¹ started using very large numbers for tab IDs. As a result, the list of "tabs" became really big — we're talking 9 digits big. Checking a list with 9 digit number of items on it takes a very long time.

That array is an object now.

—-—
¹Presumably, because my non-windows machines were mostly fine

**Comment by bureau55** [comment]
Hey, sorry for my late response, i didn't get a notification that something new was posted here.
Hm, i'm new with this Github-Stuff. :P

Nice to see that you have figured out the problem in the meantime. I think so you no longer need the extension settings.
I hope your vacation was still quite relaxing despite the weak internet.
In Germany, the politicians also call the internet "Neuland". In other words: They don't care about it.

Thanks for your hard work.
Greetings

**Comment by tamius-han** [comment]
>  I think so you no longer need the extension settings.

That's correct, settings are no longer needed. If the problem persists/re-appears even after the extension gets updated, feel free to reopen this issue, though.

**Comment by Hichem47** [comment]
Hi thank you very much for the fix, it works very good now

**Comment by bcknee** [comment]
heres my settings if it helps
