### ISSUE TITLE
Twitch player crashes when bitrate goes to 0

### ISSUE THREAD

**Issue by cletus** [tamius-han/ultrawidify#209]
I've watched some streams where the streamer's OBS hangs and the bitrate goes to 0. This causes Twitch to have no bytes to serve. For whatever reason, Alternative Twitch Player then crashes (ie purple screen) and doesn't automatically recover. You have to refresh it. Ideally, this should correct itself and not crash the player.

**Comment by tamius-han** [comment]
This sounds like a problem with Alternative Twitch Player, not this extension.

Furthermore, Ultrawidify cannot run with Alternative Twitch Player, as it creates its own page. Due to browser limitations, (in general) extensions cannot access pages that are created by other extensions in your browser.
