### ISSUE TITLE
D3D11on12 working as fix

### ISSUE THREAD

**Issue by Camilink94** [tamius-han/ultrawidify#220]
I saw that Hardware acceleration was broken on Chrome, and that I have to change to OpenGL or D3D9 to fix this in chrome://flags/#use-angle

However, those to options made the chrome window dissapear from recent apps (Alt+Tab) when playing a video on fullscreen. The stretching bug was indeed fix with this though. I tried the D3D11on12 option, and it works, both for the stretching and the window appearing in the Alt+Tab menu.

Chrome v 109.0.5414.120
Ultrawidify version: 5.1.6.
Windows 10 22H2

**Comment by TechnoStone** [comment]
*Sad Edge noises* https://github.com/tamius-han/ultrawidify/issues/219#issuecomment-1400969807

**Comment by tamius-han** [comment]
Well that's the worst combo for my ANGLE backend detection script, as it doesn't seem possible to differentiate between DX11 and DX11on12 using the method I have.

I'll have to verify that on my end in the evening. 

Can I also get what graphics card you use in case D3D11on12 doesn't work as advertised for me? I'm asking because the last time this happened, AMD GPUs seemed to be immune from this issue.

**Comment by victorhgrgn** [comment]
DX11on12 seems to have fixed the issue on my end as well. I'm using an RTX 3070.
