### ISSUE TITLE
Stretching mode on Twitch stuck on "basic"

### ISSUE THREAD

**Issue by OathOfRevenge** [tamius-han/ultrawidify#223]
Despite having set stretching mode to "normal" in the extension settings and in the site settings, whenever I open a new Twitch stream it defaults back to "basic". This is a problem because the video zooms in slightly and part of it gets cropped out.

I'm using Chrome version 112.0.5615.121 on Windows 10 Pro, and Ultrawidify is version 5.1.6.

Showing the issue here, notice how the timer on the top right gets cropped:

https://user-images.githubusercontent.com/130859775/232243417-6777013b-ef63-4de7-9ed0-21bfcc5ca91d.mp4

**Comment by tamius-han** [comment]
Hi, thanks for the report. I would like to ask for two more things:

1. I see you're in theater mode. If you exit the theater mode and then enter it again (without doing anything else), does the video get cropped correctly?
2. Can I get a video that shows you opening the twitch stream from a blank tab?

Things that I'd like to see with #2:

* how quickly the twitch page loads for you
* how quickly you toggle the theater mode

Because the only way I can get this to happen is by clicking theater mode button after the player has loaded, but video is still buffering — which means I can reproduce this only if I open the theater mode in the correct interval of less than half a second.

Thanks.

Notes to self:
```
* not problem with stretching mode being stuck to basic
* is problem with player dimensions not updating if theater mode is entered too quickly. It appears that MutationObserver doesn't trigger?
```

**Comment by OathOfRevenge** [comment]
Thank you for creating such an amazing tool, I can finally unstretch those poor arcade game clips from Twitter ;)

Loved this in the store description:
>  → 4:3 (src) — not all people are men of culture. Some people torture others by posting 4:3 content stretched to 16:9. This option makes the video 4:3 again.

Back to the issue.
Exiting and re-entering theater mode does indeed fix the issue, good catch! I'm using an extension (FrankerFaceZ) to automatically open theater mode as I open any stream, which explains how unnaturally fast it enters it.

 1. Still need the video of me opening a Twitch stream?
 2. Any suggestions/workarounds on this other than "disable that setting"?

**Comment by tamius-han** [comment]
> 1. Still need the video of me opening a Twitch stream?

No, thanks. The comment provides the info I need.

> 2. Any suggestions/workarounds on this other than "disable that setting"?

So far, no — but I'll try to see if I can figure something out.

**Comment by Hichem47** [comment]
same problem on brave, it's vert annoying, I have to remove and reinstall the extenstion every boot of my pc 

thanks for help

**Comment by Hichem47** [comment]
The only way I can get it to work is to go on video setting and select basic on Stretching mode but its very annoying because it changes all player and all website

**Comment by Hichem47** [comment]
where I can get help please thx
