### ISSUE TITLE
Fit to height fails in YouTube.com standard and full screen modes (21:9 video on 16:9 screen)

### ISSUE THREAD

**Issue by ErinPo** [tamius-han/ultrawidify#231]
**Describe the bug**
Describe what happened. Don't forget to mention which site you were on (reddit, netflix, youtube). If issue only happens with certain videos, please provide links with timestamps.

**To Reproduce**
1. Open 21:9 format video on YouTube on 16:9 screen. Ex: https://www.youtube.com/watch?v=DppVAQqaNE4
2. Optionally type F on keyboard to enter fullscreen mode
3. Type E on keyboard or click fit height from ultrawidify button to fit height

**Expected behavior**
Video gets zoomed in and cropped left and right such that there are no more black borders at the top and bottom.

**Screenshots**
There is no change in the scaling or positioning of the video

**Browser and OS**
 * Browser/browser version: Firefox 115.0.2
 * Operating system: MacOS 13.5
 * Ultrawidify version: 5.1.6

**Additional info**
Only in Youtube's cinema mode (keyboard T) does fitting height work as expected (and returning to normal by reset, automatic or fit width functions). Rather than zooming and cropping, I would actually be more interested in shifting the video up such that there is a larger bottom black border for subtitles. This way the subtitles don't have to overlap the video or there is additional space for subtitles in a secondary language. I don't know if that function is supported. I only saw options for horizontal alignment, not vertical. I would like to suggest supporting vertical alignment options.

**Comment by tamius-han** [comment]
Hi,

fit to height works as intended. 

When not using automatic aspect ratio detection, the extension has no knowledge of whether video contains letterbox or not — it only sees the file dimensions. 

Fit to height ensures that file height is equal to the player height, cropping or adding pillarbox as necessary. Since the file height is already equal to the player height, nothing happens.

Fit to width scales the video until the file width is equal to the player width, cropping or adding letterbox as necessary.
