### ISSUE TITLE
Thin white vertical line on left side of video in Firefox in theater mode

### ISSUE THREAD

**Issue by SickieGit** [tamius-han/ultrawidify#240]
**Describe the bug**
When viewing video in theater mode on YouTube in Firefox on the left side of the video a vertical white line that is 1px wide will show up. When viewing in default view this does not happen. If the video has black bars and the add-on kicks in and stretches the video to proper ratio, the white line will disappear. I tested this behavior on Edge and it doesn't happen. Using the latest Firefox release, although this bug is present for a while now. The white line disappears if I manually select 16:9 aspect ratio with shortcut [S]. However if I reset the auto detection with [R] it will show up immediately.

**To Reproduce**
1. Open Firefox with Ultrawidify installed
2. Open any YouTube video that has 16:9 aspect ratio (it does not need to be corrected)
3. Observe the left side of the video for a 1px wide vertical white line

**Expected behavior**
There should be no white vertical line

**Screenshots**
![image](https://github.com/tamius-han/ultrawidify/assets/66867142/c06e9e7c-9a0c-478b-a704-2c8c734f4c8e)

**Browser and OS**
 * Browser/browser version: Firefox 121.0.1 (64-bit)
 * Operating system: Windows 10 22H2 (latest build)
 * Ultrawidify version: 5.1.6

**Comment by tamius-han** [comment]
Thanks for the bug report. Someone already messaged me about this on reddit, but I had a very busy december so I forgot about this issue (especially since it seems to be affecting only certain configurations) until this issue popped in my e-mail.

Long story short is:

* because extension runs autodetection by default, there's always some correction going on (even if there doesn't appear to be)

* when the extension centers the video, it can move something to the right by something and a half pixels

*  firefox doesn't like the '.5' part, and starts rendering a 1px white line (this part so far seems dependent on other factors)
 
I've just pushed the fix to AMO, so your Firefox should get the update soon (usually within a few days). If the issue still persists for you after the update, feel free to reopen this issue.

**Comment by SickieGit** [comment]
Just updated the add-on to 5.1.7 version and the issue is gone indeed, Thank you very much for your time and effort into making and supporting such an amazing tool! All the best!
