### ISSUE TITLE
video go all the way to the right side

### ISSUE THREAD

**Issue by Gr33nHood** [tamius-han/ultrawidify#241]
**Describe the bug**
Describe what happened. Don't forget to mention which site you were on (reddit, netflix, youtube). If issue only happens with certain videos, please provide links with timestamps.
youtube

**To Reproduce**
What did you do to make it happen? 
login to my youtube account
**Expected behavior**
What do you think should happen instead?
it need to fill and work 
**Screenshots**
A picture is worth a thousand words. If Ultrawidify scales a video in an improper way, please include a screenshot of that.
![image](https://github.com/tamius-han/ultrawidify/assets/102728244/77c2b6d3-683e-4511-aa7d-9e7d3f0c87cc)

**Browser and OS**
 * Browser/browser version:
 * brave and firefox the most updated one idk
 * Operating system:
 * windows 11
 * Ultrawidify version:
the least one 
**Additional info**
Any other things you want to say.

i see that other had my problem but the fix that they use didn't work for me

**Comment by tamius-han** [comment]
This one is fun, because things work normally for me. Though granted, I'm still on Win10, so I didn't actually test on 11 — I need to get a VM up for that.

* Do you have nVidia, AMD, or intel GPU?
* What happens after hard refresh of the page (CTRL+F5), or open youtube in a new tab?
* What happens if you press shift and move mouse cursor over the video?

**Comment by Gr33nHood** [comment]
> This one is fun, because things work normally for me. Though granted, I'm still on Win10, so I didn't actually test on 11 — I need to get a VM up for that.
> 
> * Do you have nVidia, AMD, or intel GPU?
> * What happens after hard refresh of the page (CTRL+F5), or open youtube in a new tab?
> * What happens if you press shift and move mouse cursor over the video?

Rtx 2080 Nvidia GPU  
noting
and noting 

but I kept digging and find a fix 
I have found out that adding to the CSS the command 
```css
right: auto;
```  
can fix it 
![image](https://github.com/tamius-han/ultrawidify/assets/102728244/dd4de425-2b97-42a9-a4e0-58adf43dec53)

that being said I'm not sure if it is the right fix for this problem 
I didn't check if it happened on any other sites and why it even happened in the first place

if you need any more info let me know

**Comment by tamius-han** [comment]
Three more questions:

* How long have you been using extension before this issue started happening? (Fresh install, a month, few months or more)?
* Remove that `css` that you added, so that the problem starts happening again. If you log out of youtube, does the issue go away?
* Can you do me a favour and attach your extension settings?

In Firefox, go to `about:addons`, and go to options page for Ultrawidify. At the bottom of `General settings` page, there's an `Export settings` button. Click it, save it. Attach the json file to this thread (you might need to change file extension to txt, github is sometimes annoying). 

> and why it even happened in the first place

If the reason for this issue is "google is doing A/B testing again with youtube, so only some people get this issue" I'm going to be mildly annoyed.

**Comment by Gr33nHood** [comment]
Fresh install

yes if I remove the CSS the problem is back.
if I log out of YouTube it works with no problems 
doesn't matter what browser I'm using.

I have checked it on my laptop and PC 
I get it on both of them the same problem and on my laptop I get Linux 

[ultrawidify-settings.json](https://github.com/tamius-han/ultrawidify/files/14111797/ultrawidify-settings.json)

**Comment by Gr33nHood** [comment]
one thing I have found out is that when I log out the video is playing from www. youtube.com 
and the problem start when the video runs from  account. youtube.com

![image](https://github.com/tamius-han/ultrawidify/assets/102728244/b6342783-ea67-4054-9b94-37a8a14dd44c)

**Comment by tamius-han** [comment]
Despite "cannot reproduce":

* Ultrawidify 6.0.0 will be cropping and aligning videos differently than current extension versions
* As such, this issue is considered obsolete (as it might get fixed "for free" with the upcoming change)
