### ISSUE TITLE
Setup CI (appveyor) for Chrome, Firefox and Edge to allow users to immediately test the latest commits

### ISSUE THREAD

**Issue by Insan1ty0ne** [tamius-han/ultrawidify#56]
Hello xternal7,

Most developers of open source projects these days are allowing users "early access" to their work by using CI to automatically build a new version of the app each time a new commit is made. This way users can just test the latest version for fixes / bugs. The previous release of this app (on Chrome) was September 23, 2018 and there has been significant progress made on this project since then. So, I think setting up a CI to allow users access to the latest version for testing would be a great option for something such as this. 

Thanks!

**Comment by Insan1ty0ne** [comment]
Any progress on setting up a CI? Would love to use it for my setup.

**Comment by xternal7** [comment]
Whoopsie, made some typos in the previous post. Sorry about that if you're reading this on e-mail, I just woke up and hadn't had my coffee yet.

**Comment by xternal7** [comment]
# Update: CI still not set up, but I do have a preview version now (and it should actually work)

You can test it by downloading the appropriate file, temporarily disabling the official version of extension and using the temporary version. 

Download links: ([Firefox](http://tamius.net/ultrawidify/versions-git/ultrawidify_git-4.0.0a2-fx.xpi), [Chrome](http://tamius.net/ultrawidify/versions-git/ultrawidify_git-4.0.0a2.crx)). These are self-hosted.

This time around, I'm actually looking for some feedback if you can spare the time. I'd appreciate it a lot.

# Here's what's changing

There's been a ton of changes under the hood, so possibility of things breaking is big. Most notable ones that users like you will see are:

* extension and auto-detection are enabled on all sites by default (doesn't mean it'll work everywhere. Chrome got less testing than Firefox)
* settings page has been added. You can add shortcuts (or even popup buttons) for custom aspect ratios in there, on actions page. Keyboard shortcuts are also editable (but not yet disableable).

# Things that I'm looking for

* on which sites the extension works now out of the box (bonus: does autodetection work as well?) 
* which sites are broken (I don't guarantee I'll get around to manually support those)
* auto-detection quirks (any videos where autodetection doesn't work correctly/crops too much, preferably with timestamps)
* does extension break any sites?
* performance problems
* any other feedback (except presence of logging (will be disabled) and appearance (removal of debug stuff, making color scheme slightly more consistent, padding around popup elements and stuff)
* any problems you get while trying to add or change keyboard shortcuts or actions or whatever

When reporting sites and things that don't work, please also include your browser. If reporting a performance issue, please also include your OS and PC specs.

# Things that I know so far

* clips.twitch.tv on Chrome doesn't work at all, but should work with Firefox
* vimeo doesn't work and will not work for a while (would require some special code)
* since this builds are mostly for testing, console.logs are still there. This may have a significant negative performance impact.
* When using modifier keys for keyboard shortcuts, be sure to press the modifier key first and release it last. This will probably not be fixed any time soon.
* Zoom slider is still supposed to be experimental, but doesn't have the appropriate label
* 'Reset' option doesn't reset manual zoom
* CSS is outright atrocious and some tabs aren't completely finished yet. This will be fixed before official updates.

Thanks in advance.

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### Somewhat full list of changes

* Using vue for popup and settings page
* Editable shortcuts
* Per-site controls
* You can now select which specific video on the page you control, provided each video is in its separate iframe 
* Basic mode added
* Rewrote keyboard shortcuts and changed how they're handled. Massively.
* Fixed the bug where saving settings wouldn't work
* Fixed the bug where autodetection didn't calculate aspect ratio correctly. This bug would manifest in this extension cropping too much video even in cases where edge between letterbox and video was clearly defined.
* Implemented/improved black frame detection
* Autodetection now differentiates between legitimate letterbox and linear gradients. This should prevent incorrect auto-cropping on videos that look similar to IGN's [Hollow Knight](https://www.youtube.com/watch?v=hg25ONutphA) review.

**Comment by xternal7** [comment]
This has been in the works for a while.

* The first attempt at CI (I decided to go with the gitlab was a sorta-fail, and I got distracted from it by other things)

* This time I've went around with more of a self-hosted approach to justify my server up in the attic. Firefox version seems to be getting built just fine. Chrome version is going to be a bit of a problem though, since Chrome appears to not allow instaling extensions from outside the chrome store on Windows and Mac. And signing the extension is sorta cancer. Chrome may therefore require one to load unpacked extension (built zip will be probided)

**Comment by Insan1ty0ne** [comment]
As someone who strictly uses Chrome, loading un-packed extensions from a .ZIP isn't a big deal at all. In fact, it is probably the most common way to test extensions on Chrome. I do it quite frequently, so it doesn't seem like a big issue to me!

**Comment by tamius-han** [comment]
So I finally managed to get the page with nightly releases up. Haven't tested whether those builds build proper.

https://stuff.lionsarch.tamius.net/ultrawidify

* 'Nightly' branch builds at 400 CE(S)T every day, but only if there's changes in this repo.
* 'Testing' branch is going to be used when I want someone to test a specific thing.
