### ISSUE TITLE
Full support for Edge insiders preview

### ISSUE THREAD

**Issue by GoGoris** [tamius-han/ultrawidify#82]
I tried out the new Edge Insider preview based on Chromium. This browser supports Netflix up to 4K ánd it supports Chrome plugins. 

First the good news: I tried this plugin in the new Edge Insider build and the scaling is working. I was able to watch Mindhunter on Netflix, which normallly has a black box around the video, in full screen and full HD. The video was clearly much sharper than in Firefox. (Monitor resolution: 3440x1440)

Unfortunately I also have bad news: the settings menu seems somewhat broken, the current settings are blank, the current site is not detected and settings are not persisted.

All in all I think that the results were really positive, we finally have an easy way to watch everything on Netflix in high quality ultra wide without all the hassle from the previous Edge browser. However there are still some bugs before the new Edge browser is fully supported.

Download Edge Insider Preview: https://www.microsoftedgeinsider.com/en-us/

**Comment by xternal7** [comment]
Hi, 

I haven't been quite able to reproduce the bug. For me, it works fine. Can you provide some more info on how you got it to break (including screenshots).

Some extra questions:

* Extension version?
* You did get the extension from Chrome Web Store, right?

There's some major "breaking" changes when you switch from old Edge to Chromium-based edge, and the version built for old Edge is obviously not going to work on the new Edge.

... or obviously not obvious enough. I think I need to update the readme.

**Comment by GoGoris** [comment]
Yes, I downloaded the extension from the Chrome webstore.

Version: 4.4.1
Screenshot broken site settings:
![image](https://user-images.githubusercontent.com/2930063/70393941-2877b280-19f0-11ea-8c5f-f3505a88a685.png)

**Comment by xternal7** [comment]
Reproduced. Extra notes, mostly for self:

* This doesn't happen after switching to netflix from a different tab (or switching to a different tab and back again)
* Settings do get persisted after switching to a different tab and back
* Page needs to be reloaded before site-wide settings changes get applied (doesn't happen in FF/Chrome)
* likely a problem with Comms classes or storage.

**Comment by tamius-han** [comment]
**Status update:**

* Chromium edge is out of beta. The word on the street is that [extension submissions are open](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension), so that's gonna happen some time in the future.
* Current goal is to have version 4.4.5 (the next version, as of time of writing, will be 4.4.4) out for Edge as well.
* ETA: anywhere between end of February and end of March, but I'm known for blowing my deadlines because that's what happens with hobbies and side projects

**Comment by tamius-han** [comment]
**Status update II**

As of yesterday, 4.4.4 is out, which means Edge is being looked into. There's few additional things that need to be looked into before this goes out, but it appears that I've managed to get popup to work in Edge.

_If you feel adventurous:_ 

[Test/preview version](https://stuff.lionsarch.tamius.net/ultrawidify/testing/) is up if you wanna give it a spin (2002.08.82, Chrome/chromium). [Installation instructions here](https://stuff.lionsarch.tamius.net/ultrawidify/). Follow Chrome instructions, except  the URL which is `edge://extensions/` for edge.

**Comment by tamius-han** [comment]
**Status update III**

Almost right on the money. After having some unexpected issues with version 4.4.4,I've finally managed to submit a version to Microsoft store (who appears to have stopped charging 15 fucking euros for the privilege as well, so that's also nice!). Now it only needs to pass the review, which is going to take ... who knows how long. 

Side note - Opera will get its own, separate version, too. [Currently available for Opera **Beta** and Opera **Developer**](https://addons.opera.com/en-gb/extensions/details/ultrawidify/) (the link will 404 for mainline Opera and other browsers).

**Comment by tamius-han** [comment]
**Status update IV**

And we finally have [official Edge version](https://microsoftedge.microsoft.com/addons/detail/lmpgpgechmkkkehkihpiddbcbgibokbi).
