### ISSUE TITLE
Videos appear cropped to the side in youtube through Chrome

### ISSUE THREAD

**Issue by i4y** [tamius-han/ultrawidify#95]
**Describe the bug**
Describe what happened. Don't forget to mention which site you were on (reddit, netflix, youtube). If issue only happens with certain videos, please provide links with timestamps.
Videos appear cropped to the side in youtube through Chrome. Pressing "reset" in the extension does not fix it, nor does any other selection.
**To Reproduce**
What did you do to make it happen? 
![image](https://user-images.githubusercontent.com/58666145/74596975-dc1aa580-5024-11ea-99da-77985cdb99ac.png)
When exiting Full Screen the video is lost:
![image](https://user-images.githubusercontent.com/58666145/74596992-2439c800-5025-11ea-85e5-fe4600c4a590.png)

**Expected behavior**
What do you think should happen instead?

**Screenshots**
A picture is worth a thousand words. If Ultrawidify scales a video in an improper way, please include a screenshot of that.

**Browser and OS**
 * Browser/browser version: Version Chrome 79.0.3945.130
 * Operating system: Windows 10
 * Ultrawidify version: 4.4.4

**Additional info**
Any other things you want to say.

**Comment by phylop** [comment]
I have this issue as well.  Sometimes I can get it to properly center/zoom the video after i minimize/maximize the video, but then there's the added issue of the video playing on a blank background after you minimize it.

**Comment by tamius-han** [comment]
Press 'R' (or any other manual 'fit aspect ratio' key) and it should reset properly.

> Chrome
> Ultrawidify version: 4.4.4

Sounds a lot like Ultrawidify is still being held up in review by the Chrome Web Store. [Since 11th](https://addons.mozilla.org/en-GB/firefox/addon/ultrawidify/), if Mozilla version is to be believed. What can I say, Chrome web store is trash.

And oh look, it is, in fact, still being held up for review.
![image](https://user-images.githubusercontent.com/12505802/74604799-9b249e80-50c1-11ea-85ba-7d552f743723.png)

(Says 14th because I touched the description).

**Comment by tamius-han** [comment]
:tada: :tada: :tada: Chrome store update finally went through, apparently. Time to party.

**Comment by tamius-han** [comment]
... I was duped. Chrome update _didn't_ go through yet. My dashboard lied.
