### ISSUE TITLE
Extension has stopped working completely on chrome 

### ISSUE THREAD

**Issue by njosey** [tamius-han/ultrawidify#97]
**Describe the bug**
the extension has completely stopped working, the buttons do nothing  

**To Reproduce**
literally just tried to use the plugin on chrome version: 80.0.3987.122 (Official Build) (64-bit)

**Expected behavior**
the extension should be working but it doesnt

**Screenshots**
pointless because the extension wont work

**Browser and OS**
 * Browser/browser version: Google Chrome 80.0.3987.122 (Official Build) (64-bit)
 * Operating system: Windows 10 Pro Version 1909 Build 18363.657
 * Ultrawidify version: 4.4.4

**Additional info**

**Things i have tried to fix the issue on my own**

-created a new fresh local chrome user to test the plugin and see if it was some chrome user issue, it didn't work on the newly created local chrome user

-i tried using the extension in firefox and it works perfectly fine.

-resetting the extension options in the extension itself did nothing

-tried in incognito, does nothing

-disabling hardware acceleration, does nothing

-hard refreshing pages in chrome to remove their cache

-removing the extension and adding it back again

**Things i have yet to try to fix the issue:**

**Comment by tamius-han** [comment]
Yeah, I know. Sorry for the inconvenience. There's also #95 and #93 for similar issues, both closed because the fix was already completed and submitted to the store.

Unfortunately, Chrome Web Store is taking its sweet ass time with the review process. The fix was submitted on 11th of February (if I recall correctly), so it's been about three weeks now and there's nothing I can do about that.

**Workarounds** if you aren't willing to jump ship and join Firefox master race:

* Keyboard shortcuts should still work
* Get the [latest testing build](https://stuff.lionsarch.tamius.net/ultrawidify/testing/) from here (that's the top one) and [follow the install instructions here](https://github.com/tamius-han/ultrawidify/wiki/Nightly-and-testing-versions). Remember to check whether Chrome Web Store finally published a fix.

**Comment by tamius-han** [comment]
Yay, Chrome Web Store has finally published the fixes.
